<%@ Page Title="" Language="C#" MasterPageFile="~/AdminPages/AdminCenter.Master" AutoEventWireup="true" CodeBehind="UserMenuDialog.aspx.cs" Inherits="TestAccountSystem.UserMenuDialog" %>
<%--IR.Admin.RightManager.UserMenuDialog--%>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <asp:UpdatePanel runat="server" ID="UpdatePanel1">
        <ContentTemplate>
            <div class="breadcrumbs" id="breadcrumbs">
                <ul class="breadcrumb">
                    <li><i class="fa fa-home fa-fw home-icon"></i><a href="#">主页</a> </li>
                    <li class="active">
                        <label id="lbRoleName" runat="server">角色权限设置</label>
                    </li>
                </ul>
            </div>
            <div class="page-content">
                <div class="row">
                    <div class="col-xs-12">
                        <!-- PAGE CONTENT BEGINS -->
                        <div class="row">
                            <div class="col-xs-4">
                            </div>
                            <div class="col-xs-4 text-center" style="padding-left: 0px; padding-right: 0px;">
                                <div class="row" style="margin-bottom: 5px; margin-top: 5px;">
                                    <div class="col-xs-12 text-center">
                                        <asp:Button ID="btnSave" runat="server" Text="保存" OnClick="btnSave_Click" class="btn btn-default btn-warning" />
                                    </div>
                                </div>

                                <div class="panel panel-default" style="min-height: 400px;">
                                    <div class="panel-body">
                                        <asp:Panel ID="panelUser" runat="server" ScrollBars="Auto">
                                            <asp:TreeView ID="TreeView1" runat="server" ExpandDepth="1" ShowLines="true" NodeWrap="True"
                                                AutoGenerateDataBindings="False" OnTreeNodeCheckChanged="TreeView1_TreeNodeCheckChanged"
                                                ShowCheckBoxes="All" EnableClientScript="False">
                                                <NodeStyle NodeSpacing="0px" VerticalPadding="2px" />
                                                <ParentNodeStyle />
                                                <SelectedNodeStyle BackColor="#B5B5B5" Font-Underline="False" VerticalPadding="2px" />
                                            </asp:TreeView>
                                        </asp:Panel>
                                    </div>
                                    <asp:HiddenField ID="PanelScroll" runat="server" />
                                </div>
                            </div>
                        </div>
                        <!-- PAGE CONTENT ENDS -->
                    </div>
                </div>
            </div>
           <script type="text/javascript" src="Scripts/jquery.min.js"></script>
            <script type="text/javascript">
                // 点击复选框时触发事件
                function postBackByObject() {
                    var o = window.event.srcElement;
                    if (o.tagName == "INPUT" && o.type == "checkbox") {
                        __doPostBack("ctl00_MainContent_PanelScroll", "");
                    }
                }
            </script>
            <script type="text/javascript">
                //   onclick = "SetScrollTop(0,'panelUser','PanelScroll');"
                function SetScrollTop(type, panelId, hiddenId) {
                    if (type.toString() == "0") {
                        $("#" + hiddenId).val($("#" + panelId).scrollTop());
                    }
                    else {
                        $("#" + panelId).scrollTop($("#" + hiddenId).val());
                        $("#" + panelId).scrollTop($("#" + hiddenId).val());
                    }
                }

                function Refresh() {
                    window.opener.location.href;
                }
            </script>

        </ContentTemplate>
    </asp:UpdatePanel>
</asp:Content>
